# roles/wso2_api_manager/defaults/main.yml
---
wso2_version: "4.2.0"
wso2_user: wso2
wso2_group: wso2
wso2_base_dir: /opt
wso2_home: "{{ wso2_base_dir }}/wso2am-{{ wso2_version }}"
wso2_service_name: wso2apim

wso2_download_url: "https://github.com/wso2/product-apim/releases/download/v{{ wso2_version }}/wso2am-{{ wso2_version }}.zip"

wso2_java_package: "openjdk-11-jdk"

# Ports simples (exemple)
wso2_https_port: 9443

# DB générique
wso2_db_type: "postgres"
wso2_db_host: "localhost"
wso2_db_port: 5432
wso2_db_name: "wso2apim"
wso2_db_user: "wso2apim"
wso2_db_password: "CHANGE_ME"

