# roles/wso2_api_manager/tasks/config.yml
---
- name: Générer le fichier deployment.toml
  ansible.builtin.template:
    src: "deployment.toml.j2"
    dest: "{{ wso2_home }}/repository/conf/deployment.toml"
    owner: "{{ wso2_user }}"
    group: "{{ wso2_group }}"
    mode: '0644'
  notify: restart wso2 api manager

