# roles/wso2_api_manager/tasks/main.yml
---
- name: Pré-requis système pour WSO2 API Manager
  ansible.builtin.import_tasks: prereqs.yml
  tags:
    - wso2
    - prereqs

- name: Installer WSO2 API Manager
  ansible.builtin.import_tasks: install.yml
  tags:
    - wso2
    - install

- name: Configurer WSO2 API Manager
  ansible.builtin.import_tasks: config.yml
  tags:
    - wso2
    - config

- name: Gérer le service WSO2 API Manager
  ansible.builtin.import_tasks: service.yml
  tags:
    - wso2
    - service

