# inventories/prod/group_vars/wso2_api_manager.yml
wso2_version: "4.2.0"
wso2_user: wso2
wso2_group: wso2
wso2_base_dir: /opt
wso2_home: "{{ wso2_base_dir }}/wso2am-{{ wso2_version }}"
wso2_service_name: wso2apim
wso2_download_url: "https://github.com/wso2/product-apim/releases/download/v{{ wso2_version }}/wso2am-{{ wso2_version }}.zip"

# Ports / config basique
wso2_https_port: 9443

# Exemple DB (à adapter, mettre les secrets dans Vault en vrai)
wso2_db_type: "postgres"
wso2_db_host: "db-prod.example.com"
wso2_db_port: 5432
wso2_db_name: "wso2apim"
wso2_db_user: "wso2apim"
wso2_db_password: "CHANGE_ME_IN_VAULT"

