# playbooks/install_wso2_apim.yml
---
- name: Installer et configurer WSO2 API Manager
  hosts: wso2_api_manager
  become: yes
  gather_facts: yes

  roles:
    - role: wso2_api_manager
      tags:
        - wso2

